### ISSUE TITLE
Advanced Circle CI integration

### ISSUE THREAD

**Issue by bodewig** [xmlunit/xmlunit#290]
With TravisCI we used to run on several JDKs and add some automated compatibility tests.

```yaml
    - dist: trusty
      jdk: openjdk7
    - dist: focal
      jdk: openjdk8
    - dist: focal
      jdk: openjdk10
    - dist: focal
      jdk: openjdk11
    - dist: focal
      jdk: openjdk14
    - dist: focal
      jdk: openjdk17
    - dist: trusty
      jdk: oraclejdk8
    - dist: trusty
      jdk: oraclejdk9
    - dist: focal
      jdk: oraclejdk11
script:
  - (cd compat-tests && ./hamcrest-test.sh ${VERSION} 2.2)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || test "openjdk17" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.9.1 only-assertj)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || test "openjdk17" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.13.2 only-assertj)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || test "openjdk17" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.15.0 only-assertj)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || test "openjdk17" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.19.0 both)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || test "openjdk17" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.20.2 both)
  - test "openjdk17" != "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.19.0 only-assertj3)
  - test "openjdk17" != "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./assertj-test.sh ${VERSION} 3.20.2 only-assertj3)
  - (cd compat-tests && ./jaxb-test.sh ${VERSION} javax)
  - test "openjdk7" == "${TRAVIS_JDK_VERSION}" || (cd compat-tests && ./jaxb-test.sh ${VERSION} jakarta)
```
